[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"


[build]
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[env]
ID = "0"
WIFI_SSID = "your-ssid"
WIFI_PASSWORD = "your-password"
REMOTE_ADDR = "1.2.3.4:1234"

[unstable]
build-std = ["core", "alloc"]
